include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Additional rules for library development
    public_member_api_docs: true
    avoid_print: false  # Allow print in debug mode
    prefer_single_quotes: true
    sort_pub_dependencies: true
